# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        MainWindow.setMouseTracking(True)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 13, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 33, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 53, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 73, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 93, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_units2 = QtWidgets.QLabel(self.widget)
        self.label_units2.setGeometry(QtCore.QRect(106, 73, 256, 16))
        self.label_units2.setMinimumSize(QtCore.QSize(256, 0))
        self.label_units2.setText("")
        self.label_units2.setObjectName("label_units2")
        self.label_currentUser = QtWidgets.QLabel(self.widget)
        self.label_currentUser.setGeometry(QtCore.QRect(106, 13, 91, 16))
        self.label_currentUser.setText("")
        self.label_currentUser.setObjectName("label_currentUser")
        self.label_units3 = QtWidgets.QLabel(self.widget)
        self.label_units3.setGeometry(QtCore.QRect(106, 93, 256, 16))
        self.label_units3.setMinimumSize(QtCore.QSize(256, 0))
        self.label_units3.setText("")
        self.label_units3.setObjectName("label_units3")
        self.label_username = QtWidgets.QLabel(self.widget)
        self.label_username.setGeometry(QtCore.QRect(106, 33, 256, 16))
        self.label_username.setMinimumSize(QtCore.QSize(256, 0))
        self.label_username.setText("")
        self.label_username.setObjectName("label_username")
        self.label_units1 = QtWidgets.QLabel(self.widget)
        self.label_units1.setGeometry(QtCore.QRect(106, 53, 256, 16))
        self.label_units1.setMinimumSize(QtCore.QSize(256, 0))
        self.label_units1.setText("")
        self.label_units1.setObjectName("label_units1")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(420, 78, 62, 16))
        self.label_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(420, 18, 62, 16))
        self.label_7.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(420, 38, 62, 16))
        self.label_8.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(420, 98, 62, 16))
        self.label_9.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(420, 58, 62, 16))
        self.label_10.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_10.setObjectName("label_10")
        self.label_scores = QtWidgets.QLabel(self.widget)
        self.label_scores.setGeometry(QtCore.QRect(480, 78, 256, 16))
        self.label_scores.setMinimumSize(QtCore.QSize(256, 0))
        self.label_scores.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_scores.setText("")
        self.label_scores.setObjectName("label_scores")
        self.label_default = QtWidgets.QLabel(self.widget)
        self.label_default.setGeometry(QtCore.QRect(480, 18, 256, 16))
        self.label_default.setMinimumSize(QtCore.QSize(256, 0))
        self.label_default.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_default.setText("")
        self.label_default.setObjectName("label_default")
        self.label_nums = QtWidgets.QLabel(self.widget)
        self.label_nums.setGeometry(QtCore.QRect(480, 58, 256, 16))
        self.label_nums.setMinimumSize(QtCore.QSize(256, 0))
        self.label_nums.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_nums.setText("")
        self.label_nums.setObjectName("label_nums")
        self.label_score = QtWidgets.QLabel(self.widget)
        self.label_score.setGeometry(QtCore.QRect(480, 98, 256, 16))
        self.label_score.setMinimumSize(QtCore.QSize(256, 0))
        self.label_score.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_score.setText("")
        self.label_score.setObjectName("label_score")
        self.label_testtime = QtWidgets.QLabel(self.widget)
        self.label_testtime.setGeometry(QtCore.QRect(480, 38, 256, 16))
        self.label_testtime.setMinimumSize(QtCore.QSize(256, 0))
        self.label_testtime.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_testtime.setText("")
        self.label_testtime.setObjectName("label_testtime")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(20, 114, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_currenttime = QtWidgets.QLabel(self.widget)
        self.label_currenttime.setGeometry(QtCore.QRect(106, 114, 256, 16))
        self.label_currenttime.setMinimumSize(QtCore.QSize(256, 0))
        self.label_currenttime.setText("")
        self.label_currenttime.setObjectName("label_currenttime")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(420, 120, 62, 16))
        self.label_12.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_12.setObjectName("label_12")
        self.label_scoretime = QtWidgets.QLabel(self.widget)
        self.label_scoretime.setGeometry(QtCore.QRect(480, 120, 256, 16))
        self.label_scoretime.setMinimumSize(QtCore.QSize(256, 0))
        self.label_scoretime.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_scoretime.setText("")
        self.label_scoretime.setObjectName("label_scoretime")
        self.label_picture = QtWidgets.QLabel(self.widget)
        self.label_picture.setGeometry(QtCore.QRect(870, 10, 100, 100))
        self.label_picture.setStyleSheet("")
        self.label_picture.setText("")
        self.label_picture.setObjectName("label_picture")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(10, 440, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 440, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 440, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 394))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setObjectName("listView")
        self.horizontalLayout_2.addWidget(self.listView)
        self.listView_2 = QtWidgets.QListView(self.layoutWidget)
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayout_2.addWidget(self.listView_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.listView_3 = QtWidgets.QListView(self.layoutWidget)
        self.listView_3.setObjectName("listView_3")
        self.verticalLayout_3.addWidget(self.listView_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 440, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 440, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.tableView = QtWidgets.QTableView(self.widget_3)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 481, 391))
        self.tableView.setObjectName("tableView")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setGeometry(QtCore.QRect(30, 410, 62, 16))
        self.label_13.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        self.label_14.setGeometry(QtCore.QRect(90, 410, 391, 16))
        self.label_14.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 440, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 440, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        self.menu_8 = QtWidgets.QMenu(self.menubar)
        self.menu_8.setObjectName("menu_8")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_daorutiku = QtWidgets.QAction(MainWindow)
        self.action_daorutiku.setObjectName("action_daorutiku")
        self.action_daochutiku = QtWidgets.QAction(MainWindow)
        self.action_daochutiku.setObjectName("action_daochutiku")
        self.action_qingkongtiku = QtWidgets.QAction(MainWindow)
        self.action_qingkongtiku.setObjectName("action_qingkongtiku")
        self.action_hebingtiku = QtWidgets.QAction(MainWindow)
        self.action_hebingtiku.setObjectName("action_hebingtiku")
        self.actiond_4 = QtWidgets.QAction(MainWindow)
        self.actiond_4.setText("")
        self.actiond_4.setObjectName("actiond_4")
        self.actiond_5 = QtWidgets.QAction(MainWindow)
        self.actiond_5.setObjectName("actiond_5")
        self.action_tianjiashijuan = QtWidgets.QAction(MainWindow)
        self.action_tianjiashijuan.setObjectName("action_tianjiashijuan")
        self.action_ksks = QtWidgets.QAction(MainWindow)
        self.action_ksks.setObjectName("action_ksks")
        self.action_shijuanguanli = QtWidgets.QAction(MainWindow)
        self.action_shijuanguanli.setObjectName("action_shijuanguanli")
        self.actiondk_3 = QtWidgets.QAction(MainWindow)
        self.actiondk_3.setObjectName("actiondk_3")
        self.actiondk_4 = QtWidgets.QAction(MainWindow)
        self.actiondk_4.setObjectName("actiondk_4")
        self.actiondk_5 = QtWidgets.QAction(MainWindow)
        self.actiondk_5.setObjectName("actiondk_5")
        self.actiondk_6 = QtWidgets.QAction(MainWindow)
        self.actiondk_6.setObjectName("actiondk_6")
        self.actiondk_7 = QtWidgets.QAction(MainWindow)
        self.actiondk_7.setObjectName("actiondk_7")
        self.actionuser_guanli = QtWidgets.QAction(MainWindow)
        self.actionuser_guanli.setObjectName("actionuser_guanli")
        self.actionjianshao = QtWidgets.QAction(MainWindow)
        self.actionjianshao.setObjectName("actionjianshao")
        self.actionuser_daoru = QtWidgets.QAction(MainWindow)
        self.actionuser_daoru.setObjectName("actionuser_daoru")
        self.actionuser_daochu = QtWidgets.QAction(MainWindow)
        self.actionuser_daochu.setObjectName("actionuser_daochu")
        self.action_tikuguanli = QtWidgets.QAction(MainWindow)
        self.action_tikuguanli.setObjectName("action_tikuguanli")
        self.action_importdata = QtWidgets.QAction(MainWindow)
        self.action_importdata.setObjectName("action_importdata")
        self.action_outputdata = QtWidgets.QAction(MainWindow)
        self.action_outputdata.setObjectName("action_outputdata")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.actionban = QtWidgets.QAction(MainWindow)
        self.actionban.setObjectName("actionban")
        self.action_kaishikaoshi = QtWidgets.QAction(MainWindow)
        self.action_kaishikaoshi.setObjectName("action_kaishikaoshi")
        self.actionshangyicikaoshi = QtWidgets.QAction(MainWindow)
        self.actionshangyicikaoshi.setObjectName("actionshangyicikaoshi")
        self.actionjieshukaoshi = QtWidgets.QAction(MainWindow)
        self.actionjieshukaoshi.setObjectName("actionjieshukaoshi")
        self.action_daorushijuan = QtWidgets.QAction(MainWindow)
        self.action_daorushijuan.setObjectName("action_daorushijuan")
        self.actiond_daochushijuan = QtWidgets.QAction(MainWindow)
        self.actiond_daochushijuan.setObjectName("actiond_daochushijuan")
        self.actiond_qingkongshijuan = QtWidgets.QAction(MainWindow)
        self.actiond_qingkongshijuan.setObjectName("actiond_qingkongshijuan")
        self.actiond_6 = QtWidgets.QAction(MainWindow)
        self.actiond_6.setObjectName("actiond_6")
        self.actiond_7 = QtWidgets.QAction(MainWindow)
        self.actiond_7.setObjectName("actiond_7")
        self.action_chengjitongji = QtWidgets.QAction(MainWindow)
        self.action_chengjitongji.setObjectName("action_chengjitongji")
        self.action_suiji_test = QtWidgets.QAction(MainWindow)
        self.action_suiji_test.setObjectName("action_suiji_test")
        self.action_suiji_set = QtWidgets.QAction(MainWindow)
        self.action_suiji_set.setObjectName("action_suiji_set")
        self.action_tiku_moban = QtWidgets.QAction(MainWindow)
        self.action_tiku_moban.setObjectName("action_tiku_moban")
        self.menu.addAction(self.action_importdata)
        self.menu.addAction(self.action_outputdata)
        self.menu.addAction(self.action_close)
        self.menu_2.addAction(self.action_tianjiashijuan)
        self.menu_2.addAction(self.action_shijuanguanli)
        self.menu_2.addAction(self.action_daorushijuan)
        self.menu_2.addAction(self.actiond_daochushijuan)
        self.menu_2.addAction(self.actiond_qingkongshijuan)
        self.menu_3.addAction(self.action_daorutiku)
        self.menu_3.addAction(self.action_daochutiku)
        self.menu_3.addAction(self.action_qingkongtiku)
        self.menu_3.addAction(self.action_tikuguanli)
        self.menu_4.addAction(self.actionuser_guanli)
        self.menu_4.addAction(self.actionuser_daoru)
        self.menu_4.addAction(self.actionuser_daochu)
        self.menu_5.addAction(self.actionban)
        self.menu_5.addAction(self.action_tiku_moban)
        self.menu_6.addAction(self.action_kaishikaoshi)
        self.menu_6.addAction(self.action_suiji_test)
        self.menu_6.addAction(self.action_suiji_set)
        self.menu_7.addAction(self.action_chengjitongji)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        self.listView.clicked['QModelIndex'].connect(MainWindow.row_select)
        self.listView_2.clicked['QModelIndex'].connect(MainWindow.row_select1)
        self.pushButton.clicked.connect(MainWindow.add_tiku)
        self.listView_3.clicked['QModelIndex'].connect(MainWindow.row_select2)
        self.tableView.clicked['QModelIndex'].connect(MainWindow.row_select4)
        self.pushButton_3.clicked.connect(MainWindow.start_test)
        self.pushButton_2.clicked.connect(MainWindow.delete_tiku)
        self.pushButton_4.clicked.connect(MainWindow.wrong_test)
        self.pushButton_5.clicked.connect(MainWindow.start_test4)
        self.pushButton_6.clicked.connect(MainWindow.get_testpaper)
        self.pushButton_7.clicked.connect(MainWindow.suiji_test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "考试系统"))
        self.label.setText(_translate("MainWindow", "当前登录用户："))
        self.label_2.setText(_translate("MainWindow", "姓　　　　名："))
        self.label_3.setText(_translate("MainWindow", "一 级  单 位："))
        self.label_4.setText(_translate("MainWindow", "二 级  单 位："))
        self.label_5.setText(_translate("MainWindow", "三 级  单 位："))
        self.label_6.setText(_translate("MainWindow", "总　　分："))
        self.label_7.setText(_translate("MainWindow", "当前试卷："))
        self.label_8.setText(_translate("MainWindow", "考试时长："))
        self.label_9.setText(_translate("MainWindow", "得　　分："))
        self.label_10.setText(_translate("MainWindow", "题目数量："))
        self.label_11.setText(_translate("MainWindow", "当 前  时 间："))
        self.label_12.setText(_translate("MainWindow", "考试时间："))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.pushButton_2.setText(_translate("MainWindow", "删除"))
        self.pushButton_3.setText(_translate("MainWindow", "模拟练习"))
        self.pushButton_4.setText(_translate("MainWindow", "我的错题"))
        self.pushButton_6.setText(_translate("MainWindow", "生成试卷"))
        self.label_13.setText(_translate("MainWindow", "当前试卷："))
        self.pushButton_5.setText(_translate("MainWindow", "开始考试"))
        self.pushButton_7.setText(_translate("MainWindow", "随机考试"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "试卷"))
        self.menu_3.setTitle(_translate("MainWindow", "题库"))
        self.menu_4.setTitle(_translate("MainWindow", "用户"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.menu_6.setTitle(_translate("MainWindow", "考试"))
        self.menu_7.setTitle(_translate("MainWindow", "统计"))
        self.menu_8.setTitle(_translate("MainWindow", "工具"))
        self.action_daorutiku.setText(_translate("MainWindow", "导入题库"))
        self.action_daochutiku.setText(_translate("MainWindow", "导出题库"))
        self.action_qingkongtiku.setText(_translate("MainWindow", "清空题库"))
        self.action_hebingtiku.setText(_translate("MainWindow", "合并题库"))
        self.actiond_5.setText(_translate("MainWindow", "d"))
        self.action_tianjiashijuan.setText(_translate("MainWindow", "添加试卷"))
        self.action_ksks.setText(_translate("MainWindow", "开始考试"))
        self.action_shijuanguanli.setText(_translate("MainWindow", "试卷管理"))
        self.actiondk_3.setText(_translate("MainWindow", "dk"))
        self.actiondk_4.setText(_translate("MainWindow", "dk"))
        self.actiondk_5.setText(_translate("MainWindow", "dk"))
        self.actiondk_6.setText(_translate("MainWindow", "dk"))
        self.actiondk_7.setText(_translate("MainWindow", "dk"))
        self.actionuser_guanli.setText(_translate("MainWindow", "用户管理"))
        self.actionjianshao.setText(_translate("MainWindow", "删除用户"))
        self.actionuser_daoru.setText(_translate("MainWindow", "导入用户"))
        self.actionuser_daochu.setText(_translate("MainWindow", "导出用户"))
        self.action_tikuguanli.setText(_translate("MainWindow", "题库管理"))
        self.action_importdata.setText(_translate("MainWindow", "导入考试数据"))
        self.action_outputdata.setText(_translate("MainWindow", "导出考试数据"))
        self.action_close.setText(_translate("MainWindow", "关闭"))
        self.actionban.setText(_translate("MainWindow", "帮助文档"))
        self.action_kaishikaoshi.setText(_translate("MainWindow", "开始考试"))
        self.actionshangyicikaoshi.setText(_translate("MainWindow", "结束考试"))
        self.actionjieshukaoshi.setText(_translate("MainWindow", "继续考试"))
        self.action_daorushijuan.setText(_translate("MainWindow", "导入试卷"))
        self.actiond_daochushijuan.setText(_translate("MainWindow", "导出试卷"))
        self.actiond_qingkongshijuan.setText(_translate("MainWindow", "清空试卷"))
        self.actiond_6.setText(_translate("MainWindow", "d"))
        self.actiond_7.setText(_translate("MainWindow", "d"))
        self.action_chengjitongji.setText(_translate("MainWindow", "成绩统计"))
        self.action_suiji_test.setText(_translate("MainWindow", "随机考试"))
        self.action_suiji_set.setText(_translate("MainWindow", "随机设置"))
        self.action_tiku_moban.setText(_translate("MainWindow", "题库模板"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
