# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suiji_set.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(275, 312)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(200, 200))
        Form.setMaximumSize(QtCore.QSize(600, 400))
        self.lineEdit_num_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_num_1.setGeometry(QtCore.QRect(69, 14, 50, 20))
        self.lineEdit_num_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_num_1.setObjectName("lineEdit_num_1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(27, 18, 54, 12))
        self.label_3.setObjectName("label_3")
        self.lineEdit_num_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_num_2.setGeometry(QtCore.QRect(70, 60, 50, 20))
        self.lineEdit_num_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_num_2.setObjectName("lineEdit_num_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(28, 64, 54, 12))
        self.label_4.setObjectName("label_4")
        self.lineEdit_num_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_num_3.setGeometry(QtCore.QRect(71, 110, 50, 20))
        self.lineEdit_num_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_num_3.setObjectName("lineEdit_num_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(29, 114, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_num_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_num_4.setGeometry(QtCore.QRect(71, 160, 50, 20))
        self.lineEdit_num_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_num_4.setObjectName("lineEdit_num_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(29, 164, 54, 12))
        self.label_6.setObjectName("label_6")
        self.lineEdit_num_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_num_5.setGeometry(QtCore.QRect(72, 200, 50, 20))
        self.lineEdit_num_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_num_5.setObjectName("lineEdit_num_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 204, 54, 12))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(80, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 250, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_panduan_2 = QtWidgets.QLabel(Form)
        self.label_panduan_2.setGeometry(QtCore.QRect(170, 114, 54, 12))
        self.label_panduan_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_panduan_2.setObjectName("label_panduan_2")
        self.label_duoxuan_2 = QtWidgets.QLabel(Form)
        self.label_duoxuan_2.setGeometry(QtCore.QRect(170, 64, 54, 12))
        self.label_duoxuan_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_duoxuan_2.setObjectName("label_duoxuan_2")
        self.label_wenda_2 = QtWidgets.QLabel(Form)
        self.label_wenda_2.setGeometry(QtCore.QRect(170, 204, 54, 12))
        self.label_wenda_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_wenda_2.setObjectName("label_wenda_2")
        self.label_danxuan_2 = QtWidgets.QLabel(Form)
        self.label_danxuan_2.setGeometry(QtCore.QRect(170, 16, 54, 12))
        self.label_danxuan_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_danxuan_2.setObjectName("label_danxuan_2")
        self.label_tiankong_2 = QtWidgets.QLabel(Form)
        self.label_tiankong_2.setGeometry(QtCore.QRect(170, 164, 54, 12))
        self.label_tiankong_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_tiankong_2.setObjectName("label_tiankong_2")
        self.lineEdit_val_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_val_1.setGeometry(QtCore.QRect(197, 14, 50, 20))
        self.lineEdit_val_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_val_1.setObjectName("lineEdit_val_1")
        self.lineEdit_val_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_val_2.setGeometry(QtCore.QRect(198, 60, 50, 20))
        self.lineEdit_val_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_val_2.setObjectName("lineEdit_val_2")
        self.lineEdit_val_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_val_3.setGeometry(QtCore.QRect(199, 110, 50, 20))
        self.lineEdit_val_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_val_3.setObjectName("lineEdit_val_3")
        self.lineEdit_val_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_val_4.setGeometry(QtCore.QRect(199, 160, 50, 20))
        self.lineEdit_val_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_val_4.setObjectName("lineEdit_val_4")
        self.lineEdit_val_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_val_5.setGeometry(QtCore.QRect(200, 200, 50, 20))
        self.lineEdit_val_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_val_5.setObjectName("lineEdit_val_5")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.on_clicked)
        self.pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_num_1, self.lineEdit_val_1)
        Form.setTabOrder(self.lineEdit_val_1, self.lineEdit_num_2)
        Form.setTabOrder(self.lineEdit_num_2, self.lineEdit_val_2)
        Form.setTabOrder(self.lineEdit_val_2, self.lineEdit_num_3)
        Form.setTabOrder(self.lineEdit_num_3, self.lineEdit_val_3)
        Form.setTabOrder(self.lineEdit_val_3, self.lineEdit_num_4)
        Form.setTabOrder(self.lineEdit_num_4, self.lineEdit_val_4)
        Form.setTabOrder(self.lineEdit_val_4, self.pushButton)
        Form.setTabOrder(self.pushButton, self.lineEdit_val_5)
        Form.setTabOrder(self.lineEdit_val_5, self.lineEdit_num_5)
        Form.setTabOrder(self.lineEdit_num_5, self.pushButton_2)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "随机考试设置"))
        self.lineEdit_num_1.setText(_translate("Form", "0"))
        self.label_3.setText(_translate("Form", "单选题"))
        self.lineEdit_num_2.setText(_translate("Form", "0"))
        self.label_4.setText(_translate("Form", "多选题"))
        self.lineEdit_num_3.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "判断题"))
        self.lineEdit_num_4.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "填空题"))
        self.lineEdit_num_5.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "问答题"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.pushButton_2.setText(_translate("Form", "退出"))
        self.label_panduan_2.setText(_translate("Form", "分值"))
        self.label_duoxuan_2.setText(_translate("Form", "分值"))
        self.label_wenda_2.setText(_translate("Form", "分值"))
        self.label_danxuan_2.setText(_translate("Form", "分值"))
        self.label_tiankong_2.setText(_translate("Form", "分值"))
        self.lineEdit_val_1.setText(_translate("Form", "1"))
        self.lineEdit_val_2.setText(_translate("Form", "1"))
        self.lineEdit_val_3.setText(_translate("Form", "1"))
        self.lineEdit_val_4.setText(_translate("Form", "1"))
        self.lineEdit_val_5.setText(_translate("Form", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
